// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Audio stream resource.
public struct AudioStream: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The codec for this audio stream. The default is `aac`.
  ///
  /// Supported audio codecs:
  ///
  /// - `aac`
  /// - `aac-he`
  /// - `aac-he-v2`
  /// - `mp3`
  /// - `ac3`
  /// - `eac3`
  /// - `vorbis`
  public var codec: Swift.String = Swift.String()

  /// Required. Audio bitrate in bits per second. Must be between 1 and
  /// 10,000,000.
  public var bitrateBps: Swift.Int32 = Swift.Int32()

  /// Number of audio channels. Must be between 1 and 6. The default is 2.
  public var channelCount: Swift.Int32 = Swift.Int32()

  /// A list of channel names specifying layout of the audio channels.
  /// This only affects the metadata embedded in the container headers, if
  /// supported by the specified format. The default is `["fl", "fr"]`.
  ///
  /// Supported channel names:
  ///
  /// - `fl` - Front left channel
  /// - `fr` - Front right channel
  /// - `sl` - Side left channel
  /// - `sr` - Side right channel
  /// - `fc` - Front center channel
  /// - `lfe` - Low frequency
  public var channelLayout: [Swift.String] = []

  /// The mapping for the
  /// [JobConfig.edit_list][google.cloud.video.transcoder.v1.JobConfig.edit_list]
  /// atoms with audio
  /// [EditAtom.inputs][google.cloud.video.transcoder.v1.EditAtom.inputs].
  ///
  /// [google.cloud.video.transcoder.v1.EditAtom.inputs]: <doc:EditAtom/inputs>
  /// [google.cloud.video.transcoder.v1.JobConfig.edit_list]: <doc:JobConfig/editList>
  public var mapping: [AudioStream.AudioMapping] = []

  /// The audio sample rate in Hertz. The default is 48000 Hertz.
  public var sampleRateHertz: Swift.Int32 = Swift.Int32()

  /// The BCP-47 language code, such as `en-US` or `sr-Latn`. For more
  /// information, see
  /// https://www.unicode.org/reports/tr35/#Unicode_locale_identifier. Not
  /// supported in MP4 files.
  public var languageCode: Swift.String = Swift.String()

  /// The name for this particular audio stream that
  /// will be added to the HLS/DASH manifest. Not supported in MP4 files.
  public var displayName: Swift.String = Swift.String()

  /// Initialize a new instance of `AudioStream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AudioStream().with { $0.codec = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The mapping for the
  /// [JobConfig.edit_list][google.cloud.video.transcoder.v1.JobConfig.edit_list]
  /// atoms with audio
  /// [EditAtom.inputs][google.cloud.video.transcoder.v1.EditAtom.inputs].
  ///
  /// [google.cloud.video.transcoder.v1.EditAtom.inputs]: <doc:EditAtom/inputs>
  /// [google.cloud.video.transcoder.v1.JobConfig.edit_list]: <doc:JobConfig/editList>
  public struct AudioMapping: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The
    /// [EditAtom.key][google.cloud.video.transcoder.v1.EditAtom.key] that
    /// references the atom with audio inputs in the
    /// [JobConfig.edit_list][google.cloud.video.transcoder.v1.JobConfig.edit_list].
    ///
    /// [google.cloud.video.transcoder.v1.EditAtom.key]: <doc:EditAtom/key>
    /// [google.cloud.video.transcoder.v1.JobConfig.edit_list]: <doc:JobConfig/editList>
    public var atomKey: Swift.String = Swift.String()

    /// Required. The [Input.key][google.cloud.video.transcoder.v1.Input.key]
    /// that identifies the input file.
    ///
    /// [google.cloud.video.transcoder.v1.Input.key]: <doc:Input/key>
    public var inputKey: Swift.String = Swift.String()

    /// Required. The zero-based index of the track in the input file.
    public var inputTrack: Swift.Int32 = Swift.Int32()

    /// Required. The zero-based index of the channel in the input audio stream.
    public var inputChannel: Swift.Int32 = Swift.Int32()

    /// Required. The zero-based index of the channel in the output audio stream.
    public var outputChannel: Swift.Int32 = Swift.Int32()

    /// Audio volume control in dB. Negative values decrease volume,
    /// positive values increase. The default is 0.
    public var gainDb: Swift.Double = Swift.Double()

    /// Initialize a new instance of `AudioMapping`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AudioMapping().with { $0.atomKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.AudioStream.AudioMapping"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.AudioStream"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
