// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Edit atom.
public struct EditAtom: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A unique key for this atom. Must be specified when using advanced
  /// mapping.
  public var key: Swift.String = Swift.String()

  /// List of [Input.key][google.cloud.video.transcoder.v1.Input.key] values
  /// identifying files that should be used in this atom. The listed `inputs`
  /// must have the same timeline.
  ///
  /// [google.cloud.video.transcoder.v1.Input.key]: <doc:Input/key>
  public var inputs: [Swift.String] = []

  /// End time in seconds for the atom, relative to the input file timeline.
  /// When `end_time_offset` is not specified, the `inputs` are used until
  /// the end of the atom.
  public var endTimeOffset: GoogleCloudWkt.Duration? = nil

  /// Start time in seconds for the atom, relative to the input file timeline.
  /// The default is `0s`.
  public var startTimeOffset: GoogleCloudWkt.Duration? = nil

  /// Initialize a new instance of `EditAtom`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EditAtom().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.EditAtom"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
