// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Encryption settings.
public struct Encryption: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Identifier for this set of encryption options.
  public var id: Swift.String = Swift.String()

  /// Required. DRM system(s) to use; at least one must be specified. If a
  /// DRM system is omitted, it is considered disabled.
  public var drmSystems: Encryption.DrmSystems? = nil

  /// Encryption mode can be either `aes` or `cenc`.
  public var encryptionMode: OneOf_EncryptionMode? = nil

  /// Defines where content keys are stored.
  public var secretSource: OneOf_SecretSource? = nil

  /// Initialize a new instance of `Encryption`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Encryption().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case id = "id"
    case aes128 = "aes128"
    case sampleAes = "sampleAes"
    case mpegCenc = "mpegCenc"
    case secretManagerKeySource = "secretManagerKeySource"
    case drmSystems = "drmSystems"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.drmSystems = try container.decodeIfPresent(Encryption.DrmSystems.self, forKey: .drmSystems)

    var encryptionMode: OneOf_EncryptionMode? = nil
    let encryptionModeCheckAndSet = {
      if encryptionMode != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'encryptionMode'"))
      }
      encryptionMode = $0
    }
    if let aes128 = try container.decodeIfPresent(
      Encryption.Aes128Encryption?.self, forKey: .aes128)
    {
      try encryptionModeCheckAndSet(.aes128(aes128))
    }
    if let sampleAes = try container.decodeIfPresent(
      Encryption.SampleAesEncryption?.self, forKey: .sampleAes)
    {
      try encryptionModeCheckAndSet(.sampleAes(sampleAes))
    }
    if let mpegCenc = try container.decodeIfPresent(
      Encryption.MpegCommonEncryption?.self, forKey: .mpegCenc)
    {
      try encryptionModeCheckAndSet(.mpegCenc(mpegCenc))
    }
    self.encryptionMode = encryptionMode

    var secretSource: OneOf_SecretSource? = nil
    let secretSourceCheckAndSet = {
      if secretSource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'secretSource'"))
      }
      secretSource = $0
    }
    if let secretManagerKeySource = try container.decodeIfPresent(
      Encryption.SecretManagerSource?.self, forKey: .secretManagerKeySource)
    {
      try secretSourceCheckAndSet(.secretManagerKeySource(secretManagerKeySource))
    }
    self.secretSource = secretSource
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.drmSystems, forKey: .drmSystems)

    if let choice = self.encryptionMode {
      switch choice {
      case .aes128(let value):
        try container.encode(value, forKey: .aes128)
      case .sampleAes(let value):
        try container.encode(value, forKey: .sampleAes)
      case .mpegCenc(let value):
        try container.encode(value, forKey: .mpegCenc)
      }
    }

    if let choice = self.secretSource {
      switch choice {
      case .secretManagerKeySource(let value):
        try container.encode(value, forKey: .secretManagerKeySource)
      }
    }
  }

  /// Configuration for AES-128 encryption.
  public struct Aes128Encryption: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `Aes128Encryption`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Aes128Encryption().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Encryption.Aes128Encryption"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for SAMPLE-AES encryption.
  public struct SampleAesEncryption: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `SampleAesEncryption`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SampleAesEncryption().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Encryption.SampleAesEncryption"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for MPEG Common Encryption (MPEG-CENC).
  public struct MpegCommonEncryption: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Specify the encryption scheme.
    ///
    /// Supported encryption schemes:
    ///
    /// - `cenc`
    /// - `cbcs`
    public var scheme: Swift.String = Swift.String()

    /// Initialize a new instance of `MpegCommonEncryption`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MpegCommonEncryption().with { $0.scheme = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Encryption.MpegCommonEncryption"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for secrets stored in Google Secret Manager.
  public struct SecretManagerSource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The name of the Secret Version containing the encryption key in
    /// the following format:
    /// `projects/{project}/secrets/{secret_id}/versions/{version_number}`
    ///
    /// Note that only numbered versions are supported. Aliases like "latest" are
    /// not supported.
    public var secretVersion: Swift.String = Swift.String()

    /// Initialize a new instance of `SecretManagerSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SecretManagerSource().with { $0.secretVersion = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Encryption.SecretManagerSource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Widevine configuration.
  public struct Widevine: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `Widevine`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Widevine().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Encryption.Widevine"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Fairplay configuration.
  public struct Fairplay: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `Fairplay`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Fairplay().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Encryption.Fairplay"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Playready configuration.
  public struct Playready: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `Playready`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Playready().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Encryption.Playready"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Clearkey configuration.
  public struct Clearkey: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `Clearkey`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Clearkey().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Encryption.Clearkey"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines configuration for DRM systems in use.
  public struct DrmSystems: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Widevine configuration.
    public var widevine: Encryption.Widevine? = nil

    /// Fairplay configuration.
    public var fairplay: Encryption.Fairplay? = nil

    /// Playready configuration.
    public var playready: Encryption.Playready? = nil

    /// Clearkey configuration.
    public var clearkey: Encryption.Clearkey? = nil

    /// Initialize a new instance of `DrmSystems`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DrmSystems().with { $0.widevine = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Encryption.DrmSystems"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Encryption mode can be either `aes` or `cenc`.
  public enum OneOf_EncryptionMode: Codable, Equatable, Sendable {
    /// Configuration for AES-128 encryption.
    indirect case aes128(Encryption.Aes128Encryption?)
    /// Configuration for SAMPLE-AES encryption.
    indirect case sampleAes(Encryption.SampleAesEncryption?)
    /// Configuration for MPEG Common Encryption (MPEG-CENC).
    indirect case mpegCenc(Encryption.MpegCommonEncryption?)
  }

  /// Defines where content keys are stored.
  public enum OneOf_SecretSource: Codable, Equatable, Sendable {
    /// Keys are stored in Google Secret Manager.
    indirect case secretManagerKeySource(Encryption.SecretManagerSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.Encryption"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
