// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Input asset.
public struct Input: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A unique key for this input. Must be specified when using advanced
  /// mapping and edit lists.
  public var key: Swift.String = Swift.String()

  /// URI of the media. Input files must be at least 5 seconds in duration and
  /// stored in Cloud Storage (for example, `gs://bucket/inputs/file.mp4`).
  /// If empty, the value is populated from
  /// [Job.input_uri][google.cloud.video.transcoder.v1.Job.input_uri]. See
  /// [Supported input and output
  /// formats](https://cloud.google.com/transcoder/docs/concepts/supported-input-and-output-formats).
  ///
  /// [google.cloud.video.transcoder.v1.Job.input_uri]: <doc:Job/inputUri>
  public var uri: Swift.String = Swift.String()

  /// Preprocessing configurations.
  public var preprocessingConfig: PreprocessingConfig? = nil

  /// Optional. Input Attributes.
  public var attributes: InputAttributes? = nil

  /// Initialize a new instance of `Input`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Input().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.Input"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
