// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Job configuration
public struct JobConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// List of input assets stored in Cloud Storage.
  public var inputs: [Input] = []

  /// List of edit atoms. Defines the ultimate timeline of the resulting
  /// file or manifest.
  public var editList: [EditAtom] = []

  /// List of elementary streams.
  public var elementaryStreams: [ElementaryStream] = []

  /// List of multiplexing settings for output streams.
  public var muxStreams: [MuxStream] = []

  /// List of output manifests.
  public var manifests: [Manifest] = []

  /// Output configuration.
  public var output: Output? = nil

  /// List of ad breaks. Specifies where to insert ad break tags in the output
  /// manifests.
  public var adBreaks: [AdBreak] = []

  /// Destination on Pub/Sub.
  public var pubsubDestination: PubsubDestination? = nil

  /// List of output sprite sheets.
  /// Spritesheets require at least one VideoStream in the Jobconfig.
  public var spriteSheets: [SpriteSheet] = []

  /// List of overlays on the output video, in descending Z-order.
  public var overlays: [Overlay] = []

  /// List of encryption configurations for the content.
  /// Each configuration has an ID. Specify this ID in the
  /// [MuxStream.encryption_id][google.cloud.video.transcoder.v1.MuxStream.encryption_id]
  /// field to indicate the configuration to use for that `MuxStream` output.
  ///
  /// [google.cloud.video.transcoder.v1.MuxStream.encryption_id]: <doc:MuxStream/encryptionId>
  public var encryptions: [Encryption] = []

  /// Initialize a new instance of `JobConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobConfig().with { $0.inputs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.JobConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
