// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Multiplexing settings for output stream.
public struct MuxStream: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// A unique key for this multiplexed stream.
  public var key: Swift.String = Swift.String()

  /// The name of the generated file. The default is
  /// [MuxStream.key][google.cloud.video.transcoder.v1.MuxStream.key] with the
  /// extension suffix corresponding to the
  /// [MuxStream.container][google.cloud.video.transcoder.v1.MuxStream.container].
  ///
  /// Individual segments also have an incremental 10-digit zero-padded suffix
  /// starting from 0 before the extension, such as `mux_stream0000000123.ts`.
  ///
  /// [google.cloud.video.transcoder.v1.MuxStream.container]: <doc:MuxStream/container>
  /// [google.cloud.video.transcoder.v1.MuxStream.key]: <doc:MuxStream/key>
  public var fileName: Swift.String = Swift.String()

  /// The container format. The default is `mp4`
  ///
  /// Supported streaming formats:
  ///
  /// - `ts`
  /// - `fmp4`- the corresponding file extension is `.m4s`
  ///
  /// Supported standalone file formats:
  ///
  /// - `mp4`
  /// - `mp3`
  /// - `ogg`
  /// - `vtt`
  ///
  /// See also:
  /// [Supported input and output
  /// formats](https://cloud.google.com/transcoder/docs/concepts/supported-input-and-output-formats)
  public var container: Swift.String = Swift.String()

  /// List of
  /// [ElementaryStream.key][google.cloud.video.transcoder.v1.ElementaryStream.key]
  /// values multiplexed in this stream.
  ///
  /// [google.cloud.video.transcoder.v1.ElementaryStream.key]: <doc:ElementaryStream/key>
  public var elementaryStreams: [Swift.String] = []

  /// Segment settings for `ts`, `fmp4` and `vtt`.
  public var segmentSettings: SegmentSettings? = nil

  /// Identifier of the encryption configuration to use. If omitted, output will
  /// be unencrypted.
  public var encryptionId: Swift.String = Swift.String()

  /// Specifies the container configuration.
  public var containerConfig: OneOf_ContainerConfig? = nil

  /// Initialize a new instance of `MuxStream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MuxStream().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case key = "key"
    case fileName = "fileName"
    case container = "container"
    case elementaryStreams = "elementaryStreams"
    case segmentSettings = "segmentSettings"
    case encryptionId = "encryptionId"
    case fmp4 = "fmp4"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.key = try container.decode(Swift.String.self, forKey: .key)
    self.fileName = try container.decode(Swift.String.self, forKey: .fileName)
    self.container = try container.decode(Swift.String.self, forKey: .container)
    self.elementaryStreams = try container.decode([Swift.String].self, forKey: .elementaryStreams)
    self.segmentSettings = try container.decodeIfPresent(
      SegmentSettings.self, forKey: .segmentSettings)
    self.encryptionId = try container.decode(Swift.String.self, forKey: .encryptionId)

    var containerConfig: OneOf_ContainerConfig? = nil
    let containerConfigCheckAndSet = {
      if containerConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'containerConfig'"))
      }
      containerConfig = $0
    }
    if let fmp4 = try container.decodeIfPresent(MuxStream.Fmp4Config?.self, forKey: .fmp4) {
      try containerConfigCheckAndSet(.fmp4(fmp4))
    }
    self.containerConfig = containerConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.key, forKey: .key)
    try container.encode(self.fileName, forKey: .fileName)
    try container.encode(self.container, forKey: .container)
    try container.encode(self.elementaryStreams, forKey: .elementaryStreams)
    try container.encode(self.segmentSettings, forKey: .segmentSettings)
    try container.encode(self.encryptionId, forKey: .encryptionId)

    if let choice = self.containerConfig {
      switch choice {
      case .fmp4(let value):
        try container.encode(value, forKey: .fmp4)
      }
    }
  }

  /// `fmp4` container configuration.
  public struct Fmp4Config: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Specify the codec tag string that will be used in the media
    /// bitstream. When not specified, the codec appropriate value is used.
    ///
    /// Supported H265 codec tags:
    ///
    /// - `hvc1` (default)
    /// - `hev1`
    public var codecTag: Swift.String = Swift.String()

    /// Initialize a new instance of `Fmp4Config`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Fmp4Config().with { $0.codecTag = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.MuxStream.Fmp4Config"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Specifies the container configuration.
  public enum OneOf_ContainerConfig: Codable, Equatable, Sendable {
    /// Optional. `fmp4` container configuration.
    indirect case fmp4(MuxStream.Fmp4Config?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.MuxStream"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
