// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Location of output file(s) in a Cloud Storage bucket.
public struct Output: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// URI for the output file(s). For example, `gs://my-bucket/outputs/`. Must be
  /// a directory and not a top-level bucket. If empty, the value is populated
  /// from [Job.output_uri][google.cloud.video.transcoder.v1.Job.output_uri]. See
  /// [Supported input and output
  /// formats](https://cloud.google.com/transcoder/docs/concepts/supported-input-and-output-formats).
  ///
  /// [google.cloud.video.transcoder.v1.Job.output_uri]: <doc:Job/outputUri>
  public var uri: Swift.String = Swift.String()

  /// Initialize a new instance of `Output`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Output().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.Output"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
