// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Preprocessing configurations.
public struct PreprocessingConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Color preprocessing configuration.
  public var color: PreprocessingConfig.Color? = nil

  /// Denoise preprocessing configuration.
  public var denoise: PreprocessingConfig.Denoise? = nil

  /// Deblock preprocessing configuration.
  public var deblock: PreprocessingConfig.Deblock? = nil

  /// Audio preprocessing configuration.
  public var audio: PreprocessingConfig.Audio? = nil

  /// Specify the video cropping configuration.
  public var crop: PreprocessingConfig.Crop? = nil

  /// Specify the video pad filter configuration.
  public var pad: PreprocessingConfig.Pad? = nil

  /// Specify the video deinterlace configuration.
  public var deinterlace: PreprocessingConfig.Deinterlace? = nil

  /// Initialize a new instance of `PreprocessingConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PreprocessingConfig().with { $0.color = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Color preprocessing configuration.
  ///
  /// **Note:** This configuration is not supported.
  public struct Color: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Control color saturation of the video. Enter a value between -1 and 1,
    /// where -1 is fully desaturated and 1 is maximum saturation. 0 is no
    /// change. The default is 0.
    public var saturation: Swift.Double = Swift.Double()

    /// Control black and white contrast of the video. Enter a value between -1
    /// and 1, where -1 is minimum contrast and 1 is maximum contrast. 0 is no
    /// change. The default is 0.
    public var contrast: Swift.Double = Swift.Double()

    /// Control brightness of the video. Enter a value between -1 and 1, where -1
    /// is minimum brightness and 1 is maximum brightness. 0 is no change. The
    /// default is 0.
    public var brightness: Swift.Double = Swift.Double()

    /// Initialize a new instance of `Color`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Color().with { $0.saturation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.PreprocessingConfig.Color"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Denoise preprocessing configuration.
  ///
  /// **Note:** This configuration is not supported.
  public struct Denoise: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Set strength of the denoise. Enter a value between 0 and 1. The higher
    /// the value, the smoother the image. 0 is no denoising. The default is 0.
    public var strength: Swift.Double = Swift.Double()

    /// Set the denoiser mode. The default is `standard`.
    ///
    /// Supported denoiser modes:
    ///
    /// - `standard`
    /// - `grain`
    public var tune: Swift.String = Swift.String()

    /// Initialize a new instance of `Denoise`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Denoise().with { $0.strength = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.PreprocessingConfig.Denoise"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Deblock preprocessing configuration.
  ///
  /// **Note:** This configuration is not supported.
  public struct Deblock: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Set strength of the deblocker. Enter a value between 0 and 1. The higher
    /// the value, the stronger the block removal. 0 is no deblocking. The
    /// default is 0.
    public var strength: Swift.Double = Swift.Double()

    /// Enable deblocker. The default is `false`.
    public var enabled: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `Deblock`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Deblock().with { $0.strength = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.PreprocessingConfig.Deblock"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Audio preprocessing configuration.
  public struct Audio: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Specify audio loudness normalization in loudness units relative to full
    /// scale (LUFS). Enter a value between -24 and 0 (the default), where:
    ///
    /// *   -24 is the Advanced Television Systems Committee (ATSC A/85) standard
    /// *   -23 is the EU R128 broadcast standard
    /// *   -19 is the prior standard for online mono audio
    /// *   -18 is the ReplayGain standard
    /// *   -16 is the prior standard for stereo audio
    /// *   -14 is the new online audio standard recommended by Spotify, as well
    ///     as Amazon Echo
    /// *   0 disables normalization
    public var lufs: Swift.Double = Swift.Double()

    /// Enable boosting high frequency components. The default is `false`.
    ///
    /// **Note:** This field is not supported.
    public var highBoost: Swift.Bool = Swift.Bool()

    /// Enable boosting low frequency components. The default is `false`.
    ///
    /// **Note:** This field is not supported.
    public var lowBoost: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `Audio`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Audio().with { $0.lufs = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.PreprocessingConfig.Audio"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Video cropping configuration for the input video. The cropped input video
  /// is scaled to match the output resolution.
  public struct Crop: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The number of pixels to crop from the top. The default is 0.
    public var topPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to crop from the bottom. The default is 0.
    public var bottomPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to crop from the left. The default is 0.
    public var leftPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to crop from the right. The default is 0.
    public var rightPixels: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Crop`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Crop().with { $0.topPixels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.PreprocessingConfig.Crop"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Pad filter configuration for the input video. The padded input video
  /// is scaled after padding with black to match the output resolution.
  public struct Pad: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The number of pixels to add to the top. The default is 0.
    public var topPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to add to the bottom. The default is 0.
    public var bottomPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to add to the left. The default is 0.
    public var leftPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to add to the right. The default is 0.
    public var rightPixels: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Pad`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Pad().with { $0.topPixels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.PreprocessingConfig.Pad"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Deinterlace configuration for input video.
  public struct Deinterlace: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Specify the video deinterlacing filter. The default is `yadif`.
    public var deinterlacingFilter: OneOf_DeinterlacingFilter? = nil

    /// Initialize a new instance of `Deinterlace`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Deinterlace().with { $0.yadif = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case yadif = "yadif"
      case bwdif = "bwdif"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var deinterlacingFilter: OneOf_DeinterlacingFilter? = nil
      let deinterlacingFilterCheckAndSet = {
        if deinterlacingFilter != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'deinterlacingFilter'"))
        }
        deinterlacingFilter = $0
      }
      if let yadif = try container.decodeIfPresent(
        PreprocessingConfig.Deinterlace.YadifConfig?.self, forKey: .yadif)
      {
        try deinterlacingFilterCheckAndSet(.yadif(yadif))
      }
      if let bwdif = try container.decodeIfPresent(
        PreprocessingConfig.Deinterlace.BwdifConfig?.self, forKey: .bwdif)
      {
        try deinterlacingFilterCheckAndSet(.bwdif(bwdif))
      }
      self.deinterlacingFilter = deinterlacingFilter
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.deinterlacingFilter {
        switch choice {
        case .yadif(let value):
          try container.encode(value, forKey: .yadif)
        case .bwdif(let value):
          try container.encode(value, forKey: .bwdif)
        }
      }
    }

    /// Yet Another Deinterlacing Filter Configuration.
    public struct YadifConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Specifies the deinterlacing mode to adopt.
      /// The default is `send_frame`.
      /// Supported values:
      ///
      /// - `send_frame`: Output one frame for each frame
      /// - `send_field`: Output one frame for each field
      public var mode: Swift.String = Swift.String()

      /// Disable spacial interlacing.
      /// The default is `false`.
      public var disableSpatialInterlacing: Swift.Bool = Swift.Bool()

      /// The picture field parity assumed for the input interlaced video.
      /// The default is `auto`.
      /// Supported values:
      ///
      /// - `tff`: Assume the top field is first
      /// - `bff`: Assume the bottom field is first
      /// - `auto`: Enable automatic detection of field parity
      public var parity: Swift.String = Swift.String()

      /// Deinterlace all frames rather than just the frames identified as
      /// interlaced. The default is `false`.
      public var deinterlaceAllFrames: Swift.Bool = Swift.Bool()

      /// Initialize a new instance of `YadifConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = YadifConfig().with { $0.mode = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.video.transcoder.v1.PreprocessingConfig.Deinterlace.YadifConfig"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Bob Weaver Deinterlacing Filter Configuration.
    public struct BwdifConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Specifies the deinterlacing mode to adopt.
      /// The default is `send_frame`.
      /// Supported values:
      ///
      /// - `send_frame`: Output one frame for each frame
      /// - `send_field`: Output one frame for each field
      public var mode: Swift.String = Swift.String()

      /// The picture field parity assumed for the input interlaced video.
      /// The default is `auto`.
      /// Supported values:
      ///
      /// - `tff`: Assume the top field is first
      /// - `bff`: Assume the bottom field is first
      /// - `auto`: Enable automatic detection of field parity
      public var parity: Swift.String = Swift.String()

      /// Deinterlace all frames rather than just the frames identified as
      /// interlaced. The default is `false`.
      public var deinterlaceAllFrames: Swift.Bool = Swift.Bool()

      /// Initialize a new instance of `BwdifConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = BwdifConfig().with { $0.mode = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.video.transcoder.v1.PreprocessingConfig.Deinterlace.BwdifConfig"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Specify the video deinterlacing filter. The default is `yadif`.
    public enum OneOf_DeinterlacingFilter: Codable, Equatable, Sendable {
      /// Specifies the Yet Another Deinterlacing Filter Configuration.
      indirect case yadif(PreprocessingConfig.Deinterlace.YadifConfig?)
      /// Specifies the Bob Weaver Deinterlacing Filter Configuration.
      indirect case bwdif(PreprocessingConfig.Deinterlace.BwdifConfig?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.PreprocessingConfig.Deinterlace"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.PreprocessingConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
