// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Segment settings for `ts`, `fmp4` and `vtt`.
public struct SegmentSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Duration of the segments in seconds. The default is `6.0s`. Note that
  /// `segmentDuration` must be greater than or equal to
  /// [`gopDuration`](#videostream), and `segmentDuration` must be divisible by
  /// [`gopDuration`](#videostream).
  public var segmentDuration: GoogleCloudWkt.Duration? = nil

  /// Required. Create an individual segment file. The default is `false`.
  public var individualSegments: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `SegmentSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SegmentSettings().with { $0.segmentDuration = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.SegmentSettings"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
