// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Sprite sheet configuration.
public struct SpriteSheet: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Format type. The default is `jpeg`.
  ///
  /// Supported formats:
  ///
  /// - `jpeg`
  public var format: Swift.String = Swift.String()

  /// Required. File name prefix for the generated sprite sheets.
  ///
  /// Each sprite sheet has an incremental 10-digit zero-padded suffix starting
  /// from 0 before the extension, such as `sprite_sheet0000000123.jpeg`.
  public var filePrefix: Swift.String = Swift.String()

  /// Required. The width of sprite in pixels. Must be an even integer. To
  /// preserve the source aspect ratio, set the
  /// [SpriteSheet.sprite_width_pixels][google.cloud.video.transcoder.v1.SpriteSheet.sprite_width_pixels]
  /// field or the
  /// [SpriteSheet.sprite_height_pixels][google.cloud.video.transcoder.v1.SpriteSheet.sprite_height_pixels]
  /// field, but not both (the API will automatically calculate the missing
  /// field).
  ///
  /// For portrait videos that contain horizontal ASR and rotation metadata,
  /// provide the width, in pixels, per the horizontal ASR. The API calculates
  /// the height per the horizontal ASR. The API detects any rotation metadata
  /// and swaps the requested height and width for the output.
  ///
  /// [google.cloud.video.transcoder.v1.SpriteSheet.sprite_height_pixels]: <doc:SpriteSheet/spriteHeightPixels>
  /// [google.cloud.video.transcoder.v1.SpriteSheet.sprite_width_pixels]: <doc:SpriteSheet/spriteWidthPixels>
  public var spriteWidthPixels: Swift.Int32 = Swift.Int32()

  /// Required. The height of sprite in pixels. Must be an even integer. To
  /// preserve the source aspect ratio, set the
  /// [SpriteSheet.sprite_height_pixels][google.cloud.video.transcoder.v1.SpriteSheet.sprite_height_pixels]
  /// field or the
  /// [SpriteSheet.sprite_width_pixels][google.cloud.video.transcoder.v1.SpriteSheet.sprite_width_pixels]
  /// field, but not both (the API will automatically calculate the missing
  /// field).
  ///
  /// For portrait videos that contain horizontal ASR and rotation metadata,
  /// provide the height, in pixels, per the horizontal ASR. The API calculates
  /// the width per the horizontal ASR. The API detects any rotation metadata
  /// and swaps the requested height and width for the output.
  ///
  /// [google.cloud.video.transcoder.v1.SpriteSheet.sprite_height_pixels]: <doc:SpriteSheet/spriteHeightPixels>
  /// [google.cloud.video.transcoder.v1.SpriteSheet.sprite_width_pixels]: <doc:SpriteSheet/spriteWidthPixels>
  public var spriteHeightPixels: Swift.Int32 = Swift.Int32()

  /// The maximum number of sprites per row in a sprite sheet. The default is 0,
  /// which indicates no maximum limit.
  public var columnCount: Swift.Int32 = Swift.Int32()

  /// The maximum number of rows per sprite sheet. When the sprite sheet is full,
  /// a new sprite sheet is created. The default is 0, which indicates no maximum
  /// limit.
  public var rowCount: Swift.Int32 = Swift.Int32()

  /// Start time in seconds, relative to the output file timeline. Determines the
  /// first sprite to pick. The default is `0s`.
  public var startTimeOffset: GoogleCloudWKT.Duration? = nil

  /// End time in seconds, relative to the output file timeline. When
  /// `end_time_offset` is not specified, the sprites are generated until the end
  /// of the output file.
  public var endTimeOffset: GoogleCloudWKT.Duration? = nil

  /// The quality of the generated sprite sheet. Enter a value between 1
  /// and 100, where 1 is the lowest quality and 100 is the highest quality.
  /// The default is 100. A high quality value corresponds to a low image data
  /// compression ratio.
  public var quality: Swift.Int32 = Swift.Int32()

  /// Specify either total number of sprites or interval to create sprites.
  public var extractionStrategy: OneOf_ExtractionStrategy? = nil

  /// Initialize a new instance of `SpriteSheet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SpriteSheet().with { $0.format = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case format = "format"
    case filePrefix = "filePrefix"
    case spriteWidthPixels = "spriteWidthPixels"
    case spriteHeightPixels = "spriteHeightPixels"
    case columnCount = "columnCount"
    case rowCount = "rowCount"
    case startTimeOffset = "startTimeOffset"
    case endTimeOffset = "endTimeOffset"
    case totalCount = "totalCount"
    case interval = "interval"
    case quality = "quality"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.format = try container.decode(Swift.String.self, forKey: .format)
    self.filePrefix = try container.decode(Swift.String.self, forKey: .filePrefix)
    self.spriteWidthPixels = try container.decode(Swift.Int32.self, forKey: .spriteWidthPixels)
    self.spriteHeightPixels = try container.decode(Swift.Int32.self, forKey: .spriteHeightPixels)
    self.columnCount = try container.decode(Swift.Int32.self, forKey: .columnCount)
    self.rowCount = try container.decode(Swift.Int32.self, forKey: .rowCount)
    self.startTimeOffset = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .startTimeOffset)
    self.endTimeOffset = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .endTimeOffset)
    self.quality = try container.decode(Swift.Int32.self, forKey: .quality)

    var extractionStrategy: OneOf_ExtractionStrategy? = nil
    let extractionStrategyCheckAndSet = {
      if extractionStrategy != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'extractionStrategy'"))
      }
      extractionStrategy = $0
    }
    if let totalCount = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalCount) {
      try extractionStrategyCheckAndSet(.totalCount(totalCount))
    }
    if let interval = try container.decodeIfPresent(
      GoogleCloudWKT.Duration?.self, forKey: .interval)
    {
      try extractionStrategyCheckAndSet(.interval(interval))
    }
    self.extractionStrategy = extractionStrategy
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.format, forKey: .format)
    try container.encode(self.filePrefix, forKey: .filePrefix)
    try container.encode(self.spriteWidthPixels, forKey: .spriteWidthPixels)
    try container.encode(self.spriteHeightPixels, forKey: .spriteHeightPixels)
    try container.encode(self.columnCount, forKey: .columnCount)
    try container.encode(self.rowCount, forKey: .rowCount)
    try container.encode(self.startTimeOffset, forKey: .startTimeOffset)
    try container.encode(self.endTimeOffset, forKey: .endTimeOffset)
    try container.encode(self.quality, forKey: .quality)

    if let choice = self.extractionStrategy {
      switch choice {
      case .totalCount(let value):
        try container.encode(value, forKey: .totalCount)
      case .interval(let value):
        try container.encode(value, forKey: .interval)
      }
    }
  }

  /// Specify either total number of sprites or interval to create sprites.
  public enum OneOf_ExtractionStrategy: Codable, Equatable, Sendable {
    /// Total number of sprites. Create the specified number of sprites
    /// distributed evenly across the timeline of the output media. The default
    /// is 100.
    case totalCount(Swift.Int32)
    /// Starting from `0s`, create sprites at regular intervals. Specify the
    /// interval value in seconds.
    indirect case interval(GoogleCloudWKT.Duration?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.SpriteSheet"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
