// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Track definition for the input asset.
public struct TrackDefinition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The input track.
  public var inputTrack: Swift.Int32? = nil

  /// Optional. A list of languages spoken in the input asset, represented by a
  /// BCP 47 language code, such as "en-US" or "sr-Latn". For more information,
  /// see https://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
  public var languages: [Swift.String] = []

  /// Optional. Whether to automatically detect the languages present in the
  /// track. If true, the system will attempt to identify all the languages
  /// present in the track and populate the languages field.
  public var detectLanguages: Swift.Bool = Swift.Bool()

  /// Output only. A list of languages detected in the input asset, represented
  /// by a BCP 47 language code, such as "en-US" or "sr-Latn". For more
  /// information, see
  /// https://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
  /// This field is only populated if the detect_languages field is set to true.
  public var detectedLanguages: [Swift.String] = []

  /// Initialize a new instance of `TrackDefinition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TrackDefinition().with { $0.inputTrack = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.TrackDefinition"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
