// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class TranscoderServiceRetry: TranscoderServiceStub {
    let inner: any TranscoderServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any TranscoderServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createJob(
      request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.Job {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.Job
          in
          return try await self.inner.createJob(request: r, options: o)
        })
    }

    public func listJobs(
      request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.ListJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.ListJobsResponse
          in
          return try await self.inner.listJobs(request: r, options: o)
        })
    }

    public func getJob(
      request: GetJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.Job {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.Job
          in
          return try await self.inner.getJob(request: r, options: o)
        })
    }

    public func deleteJob(
      request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteJobRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteJob(request: r, options: o)
        })
    }

    public func createJobTemplate(
      request: CreateJobTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateJobTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.JobTemplate
          in
          return try await self.inner.createJobTemplate(request: r, options: o)
        })
    }

    public func listJobTemplates(
      request: ListJobTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.ListJobTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListJobTemplatesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.ListJobTemplatesResponse
          in
          return try await self.inner.listJobTemplates(request: r, options: o)
        })
    }

    public func getJobTemplate(
      request: GetJobTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetJobTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.JobTemplate
          in
          return try await self.inner.getJobTemplate(request: r, options: o)
        })
    }

    public func deleteJobTemplate(
      request: DeleteJobTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteJobTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteJobTemplate(request: r, options: o)
        })
    }
  }
}
