// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class TranscoderServiceLogging: TranscoderServiceStub {
    let inner: any TranscoderServiceStub
    let logger: Logger

    public init(_ inner: any TranscoderServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-video-transcoder-v1"
      logger[metadataKey: "gcp.client.service"] = "transcoder"
      logger[metadataKey: "gcp.experimental.swift.client"] = "TranscoderService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createJob(
      request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.Job {
      try await self._intercept(
        request: request,
        options: options,
        name: "createJob",
        action: {
          (r: CreateJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.Job
          in
          return try await self.inner.createJob(request: r, options: o)
        })
    }

    public func listJobs(
      request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.ListJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listJobs",
        action: {
          (r: ListJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.ListJobsResponse
          in
          return try await self.inner.listJobs(request: r, options: o)
        })
    }

    public func getJob(
      request: GetJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.Job {
      try await self._intercept(
        request: request,
        options: options,
        name: "getJob",
        action: {
          (r: GetJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.Job
          in
          return try await self.inner.getJob(request: r, options: o)
        })
    }

    public func deleteJob(
      request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteJob",
        action: { (r: DeleteJobRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteJob(request: r, options: o)
        })
    }

    public func createJobTemplate(
      request: CreateJobTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "createJobTemplate",
        action: {
          (r: CreateJobTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.JobTemplate
          in
          return try await self.inner.createJobTemplate(request: r, options: o)
        })
    }

    public func listJobTemplates(
      request: ListJobTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.ListJobTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listJobTemplates",
        action: {
          (r: ListJobTemplatesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.ListJobTemplatesResponse
          in
          return try await self.inner.listJobTemplates(request: r, options: o)
        })
    }

    public func getJobTemplate(
      request: GetJobTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "getJobTemplate",
        action: {
          (r: GetJobTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoTranscoderV1.JobTemplate
          in
          return try await self.inner.getJobTemplate(request: r, options: o)
        })
    }

    public func deleteJobTemplate(
      request: DeleteJobTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteJobTemplate",
        action: {
          (r: DeleteJobTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteJobTemplate(request: r, options: o)
        })
    }
  }
}
