// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleCloudGax

extension Clients {
  protocol TranscoderServiceStub: Sendable {
    func createJob(
      request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.Job

    func listJobs(
      request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.ListJobsResponse

    func getJob(
      request: GetJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.Job

    func deleteJob(
      request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createJobTemplate(
      request: CreateJobTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate

    func listJobTemplates(
      request: ListJobTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.ListJobTemplatesResponse

    func getJobTemplate(
      request: GetJobTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate

    func deleteJobTemplate(
      request: DeleteJobTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
