// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Video stream resource.
public struct VideoStream: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Codec settings can be h264, h265, or vp9.
  public var codecSettings: OneOf_CodecSettings? = nil

  /// Initialize a new instance of `VideoStream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoStream().with { $0.h264 = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case h264 = "h264"
    case h265 = "h265"
    case vp9 = "vp9"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var codecSettings: OneOf_CodecSettings? = nil
    let codecSettingsCheckAndSet = {
      if codecSettings != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'codecSettings'"))
      }
      codecSettings = $0
    }
    if let h264 = try container.decodeIfPresent(VideoStream.H264CodecSettings?.self, forKey: .h264)
    {
      try codecSettingsCheckAndSet(.h264(h264))
    }
    if let h265 = try container.decodeIfPresent(VideoStream.H265CodecSettings?.self, forKey: .h265)
    {
      try codecSettingsCheckAndSet(.h265(h265))
    }
    if let vp9 = try container.decodeIfPresent(VideoStream.Vp9CodecSettings?.self, forKey: .vp9) {
      try codecSettingsCheckAndSet(.vp9(vp9))
    }
    self.codecSettings = codecSettings
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.codecSettings {
      switch choice {
      case .h264(let value):
        try container.encode(value, forKey: .h264)
      case .h265(let value):
        try container.encode(value, forKey: .h265)
      case .vp9(let value):
        try container.encode(value, forKey: .vp9)
      }
    }
  }

  /// Convert the input video to a Standard Dynamic Range (SDR) video.
  public struct H264ColorFormatSDR: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `H264ColorFormatSDR`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = H264ColorFormatSDR().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.VideoStream.H264ColorFormatSDR"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Convert the input video to a Hybrid Log Gamma (HLG) video.
  public struct H264ColorFormatHLG: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `H264ColorFormatHLG`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = H264ColorFormatHLG().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.VideoStream.H264ColorFormatHLG"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// H264 codec settings.
  public struct H264CodecSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The width of the video in pixels. Must be an even integer.
    /// When not specified, the width is adjusted to match the specified height
    /// and input aspect ratio. If both are omitted, the input width is used.
    ///
    /// For portrait videos that contain horizontal ASR and rotation metadata,
    /// provide the width, in pixels, per the horizontal ASR. The API calculates
    /// the height per the horizontal ASR. The API detects any rotation metadata
    /// and swaps the requested height and width for the output.
    public var widthPixels: Swift.Int32 = Swift.Int32()

    /// The height of the video in pixels. Must be an even integer.
    /// When not specified, the height is adjusted to match the specified width
    /// and input aspect ratio. If both are omitted, the input height is used.
    ///
    /// For portrait videos that contain horizontal ASR and rotation metadata,
    /// provide the height, in pixels, per the horizontal ASR. The API calculates
    /// the width per the horizontal ASR. The API detects any rotation metadata
    /// and swaps the requested height and width for the output.
    public var heightPixels: Swift.Int32 = Swift.Int32()

    /// Required. The target video frame rate in frames per second (FPS). Must be
    /// less than or equal to 120.
    public var frameRate: Swift.Double = Swift.Double()

    /// Optional. Frame rate conversion strategy for desired frame rate. The
    /// default is `DOWNSAMPLE`.
    public var frameRateConversionStrategy: VideoStream.FrameRateConversionStrategy =
      VideoStream.FrameRateConversionStrategy()

    /// Required. The video bitrate in bits per second. The minimum value is
    /// 1,000. The maximum value is 800,000,000.
    public var bitrateBps: Swift.Int32 = Swift.Int32()

    /// Pixel format to use. The default is `yuv420p`.
    ///
    /// Supported pixel formats:
    ///
    /// - `yuv420p` pixel format
    /// - `yuv422p` pixel format
    /// - `yuv444p` pixel format
    /// - `yuv420p10` 10-bit HDR pixel format
    /// - `yuv422p10` 10-bit HDR pixel format
    /// - `yuv444p10` 10-bit HDR pixel format
    /// - `yuv420p12` 12-bit HDR pixel format
    /// - `yuv422p12` 12-bit HDR pixel format
    /// - `yuv444p12` 12-bit HDR pixel format
    public var pixelFormat: Swift.String = Swift.String()

    /// Specify the mode. The default is `vbr`.
    ///
    /// Supported rate control modes:
    ///
    /// - `vbr` - variable bitrate
    /// - `crf` - constant rate factor
    public var rateControlMode: Swift.String = Swift.String()

    /// Target CRF level. Must be between 10 and 36, where 10 is the highest
    /// quality and 36 is the most efficient compression. The default is 21.
    public var crfLevel: Swift.Int32 = Swift.Int32()

    /// Specifies whether an open Group of Pictures (GOP) structure should be
    /// allowed or not. The default is `false`.
    public var allowOpenGop: Swift.Bool = Swift.Bool()

    /// Use two-pass encoding strategy to achieve better video quality.
    /// [H264CodecSettings.rate_control_mode][google.cloud.video.transcoder.v1.VideoStream.H264CodecSettings.rate_control_mode]
    /// must be `vbr`. The default is `false`.
    ///
    /// [google.cloud.video.transcoder.v1.VideoStream.H264CodecSettings.rate_control_mode]: <doc:VideoStream/H264CodecSettings/rateControlMode>
    public var enableTwoPass: Swift.Bool = Swift.Bool()

    /// Size of the Video Buffering Verifier (VBV) buffer in bits. Must be
    /// greater than zero. The default is equal to
    /// [H264CodecSettings.bitrate_bps][google.cloud.video.transcoder.v1.VideoStream.H264CodecSettings.bitrate_bps].
    ///
    /// [google.cloud.video.transcoder.v1.VideoStream.H264CodecSettings.bitrate_bps]: <doc:VideoStream/H264CodecSettings/bitrateBps>
    public var vbvSizeBits: Swift.Int32 = Swift.Int32()

    /// Initial fullness of the Video Buffering Verifier (VBV) buffer in bits.
    /// Must be greater than zero. The default is equal to 90% of
    /// [H264CodecSettings.vbv_size_bits][google.cloud.video.transcoder.v1.VideoStream.H264CodecSettings.vbv_size_bits].
    ///
    /// [google.cloud.video.transcoder.v1.VideoStream.H264CodecSettings.vbv_size_bits]: <doc:VideoStream/H264CodecSettings/vbvSizeBits>
    public var vbvFullnessBits: Swift.Int32 = Swift.Int32()

    /// The entropy coder to use. The default is `cabac`.
    ///
    /// Supported entropy coders:
    ///
    /// - `cavlc`
    /// - `cabac`
    public var entropyCoder: Swift.String = Swift.String()

    /// Allow B-pyramid for reference frame selection. This may not be supported
    /// on all decoders. The default is `false`.
    public var bPyramid: Swift.Bool = Swift.Bool()

    /// The number of consecutive B-frames. Must be greater than or equal to
    /// zero. Must be less than
    /// [H264CodecSettings.gop_frame_count][google.cloud.video.transcoder.v1.VideoStream.H264CodecSettings.gop_frame_count]
    /// if set. The default is 0.
    ///
    /// [google.cloud.video.transcoder.v1.VideoStream.H264CodecSettings.gop_frame_count]: <doc:VideoStream/H264CodecSettings/OneOf_GopMode/gopFrameCount(_:)>
    public var bFrameCount: Swift.Int32 = Swift.Int32()

    /// Specify the intensity of the adaptive quantizer (AQ). Must be between 0
    /// and 1, where 0 disables the quantizer and 1 maximizes the quantizer. A
    /// higher value equals a lower bitrate but smoother image. The default is 0.
    public var aqStrength: Swift.Double = Swift.Double()

    /// Enforces the specified codec profile. The following profiles are
    /// supported:
    ///
    /// *   `baseline`
    /// *   `main`
    /// *   `high` (default)
    ///
    /// The available options are
    /// [FFmpeg-compatible](https://trac.ffmpeg.org/wiki/Encode/H.264#Tune).
    /// Note that certain values for this field may cause the
    /// transcoder to override other fields you set in the `H264CodecSettings`
    /// message.
    public var profile: Swift.String = Swift.String()

    /// Enforces the specified codec tune. The available options are
    /// [FFmpeg-compatible](https://trac.ffmpeg.org/wiki/Encode/H.264#Tune).
    /// Note that certain values for this field may cause the
    /// transcoder to override other fields you set in the `H264CodecSettings`
    /// message.
    public var tune: Swift.String = Swift.String()

    /// Enforces the specified codec preset. The default is `veryfast`. The
    /// available options are
    /// [FFmpeg-compatible](https://trac.ffmpeg.org/wiki/Encode/H.264#Preset).
    /// Note that certain values for this field may cause the
    /// transcoder to override other fields you set in the `H264CodecSettings`
    /// message.
    public var preset: Swift.String = Swift.String()

    /// GOP mode can be either by frame count or duration.
    public var gopMode: OneOf_GopMode? = nil

    /// Color format can be sdr or hlg.
    public var colorFormat: OneOf_ColorFormat? = nil

    /// Initialize a new instance of `H264CodecSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = H264CodecSettings().with { $0.widthPixels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case widthPixels = "widthPixels"
      case heightPixels = "heightPixels"
      case frameRate = "frameRate"
      case frameRateConversionStrategy = "frameRateConversionStrategy"
      case bitrateBps = "bitrateBps"
      case pixelFormat = "pixelFormat"
      case rateControlMode = "rateControlMode"
      case crfLevel = "crfLevel"
      case allowOpenGop = "allowOpenGop"
      case gopFrameCount = "gopFrameCount"
      case gopDuration = "gopDuration"
      case enableTwoPass = "enableTwoPass"
      case vbvSizeBits = "vbvSizeBits"
      case vbvFullnessBits = "vbvFullnessBits"
      case entropyCoder = "entropyCoder"
      case bPyramid = "bPyramid"
      case bFrameCount = "bFrameCount"
      case aqStrength = "aqStrength"
      case profile = "profile"
      case tune = "tune"
      case preset = "preset"
      case sdr = "sdr"
      case hlg = "hlg"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.widthPixels = try container.decode(Swift.Int32.self, forKey: .widthPixels)
      self.heightPixels = try container.decode(Swift.Int32.self, forKey: .heightPixels)
      self.frameRate = try container.decode(Swift.Double.self, forKey: .frameRate)
      self.frameRateConversionStrategy = try container.decode(
        VideoStream.FrameRateConversionStrategy.self, forKey: .frameRateConversionStrategy)
      self.bitrateBps = try container.decode(Swift.Int32.self, forKey: .bitrateBps)
      self.pixelFormat = try container.decode(Swift.String.self, forKey: .pixelFormat)
      self.rateControlMode = try container.decode(Swift.String.self, forKey: .rateControlMode)
      self.crfLevel = try container.decode(Swift.Int32.self, forKey: .crfLevel)
      self.allowOpenGop = try container.decode(Swift.Bool.self, forKey: .allowOpenGop)
      self.enableTwoPass = try container.decode(Swift.Bool.self, forKey: .enableTwoPass)
      self.vbvSizeBits = try container.decode(Swift.Int32.self, forKey: .vbvSizeBits)
      self.vbvFullnessBits = try container.decode(Swift.Int32.self, forKey: .vbvFullnessBits)
      self.entropyCoder = try container.decode(Swift.String.self, forKey: .entropyCoder)
      self.bPyramid = try container.decode(Swift.Bool.self, forKey: .bPyramid)
      self.bFrameCount = try container.decode(Swift.Int32.self, forKey: .bFrameCount)
      self.aqStrength = try container.decode(Swift.Double.self, forKey: .aqStrength)
      self.profile = try container.decode(Swift.String.self, forKey: .profile)
      self.tune = try container.decode(Swift.String.self, forKey: .tune)
      self.preset = try container.decode(Swift.String.self, forKey: .preset)

      var gopMode: OneOf_GopMode? = nil
      let gopModeCheckAndSet = {
        if gopMode != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'gopMode'"))
        }
        gopMode = $0
      }
      if let gopFrameCount = try container.decodeIfPresent(Swift.Int32.self, forKey: .gopFrameCount)
      {
        try gopModeCheckAndSet(.gopFrameCount(gopFrameCount))
      }
      if let gopDuration = try container.decodeIfPresent(
        GoogleCloudWkt.Duration?.self, forKey: .gopDuration)
      {
        try gopModeCheckAndSet(.gopDuration(gopDuration))
      }
      self.gopMode = gopMode

      var colorFormat: OneOf_ColorFormat? = nil
      let colorFormatCheckAndSet = {
        if colorFormat != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'colorFormat'"))
        }
        colorFormat = $0
      }
      if let sdr = try container.decodeIfPresent(VideoStream.H264ColorFormatSDR?.self, forKey: .sdr)
      {
        try colorFormatCheckAndSet(.sdr(sdr))
      }
      if let hlg = try container.decodeIfPresent(VideoStream.H264ColorFormatHLG?.self, forKey: .hlg)
      {
        try colorFormatCheckAndSet(.hlg(hlg))
      }
      self.colorFormat = colorFormat
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.widthPixels, forKey: .widthPixels)
      try container.encode(self.heightPixels, forKey: .heightPixels)
      try container.encode(self.frameRate, forKey: .frameRate)
      try container.encode(self.frameRateConversionStrategy, forKey: .frameRateConversionStrategy)
      try container.encode(self.bitrateBps, forKey: .bitrateBps)
      try container.encode(self.pixelFormat, forKey: .pixelFormat)
      try container.encode(self.rateControlMode, forKey: .rateControlMode)
      try container.encode(self.crfLevel, forKey: .crfLevel)
      try container.encode(self.allowOpenGop, forKey: .allowOpenGop)
      try container.encode(self.enableTwoPass, forKey: .enableTwoPass)
      try container.encode(self.vbvSizeBits, forKey: .vbvSizeBits)
      try container.encode(self.vbvFullnessBits, forKey: .vbvFullnessBits)
      try container.encode(self.entropyCoder, forKey: .entropyCoder)
      try container.encode(self.bPyramid, forKey: .bPyramid)
      try container.encode(self.bFrameCount, forKey: .bFrameCount)
      try container.encode(self.aqStrength, forKey: .aqStrength)
      try container.encode(self.profile, forKey: .profile)
      try container.encode(self.tune, forKey: .tune)
      try container.encode(self.preset, forKey: .preset)

      if let choice = self.gopMode {
        switch choice {
        case .gopFrameCount(let value):
          try container.encode(value, forKey: .gopFrameCount)
        case .gopDuration(let value):
          try container.encode(value, forKey: .gopDuration)
        }
      }

      if let choice = self.colorFormat {
        switch choice {
        case .sdr(let value):
          try container.encode(value, forKey: .sdr)
        case .hlg(let value):
          try container.encode(value, forKey: .hlg)
        }
      }
    }

    /// GOP mode can be either by frame count or duration.
    public enum OneOf_GopMode: Codable, Equatable, Sendable {
      /// Select the GOP size based on the specified frame count. Must be greater
      /// than zero.
      case gopFrameCount(Swift.Int32)
      /// Select the GOP size based on the specified duration. The default is
      /// `3s`. Note that `gopDuration` must be less than or equal to
      /// [`segmentDuration`](#SegmentSettings), and
      /// [`segmentDuration`](#SegmentSettings) must be divisible by
      /// `gopDuration`.
      indirect case gopDuration(GoogleCloudWkt.Duration?)
    }

    /// Color format can be sdr or hlg.
    public enum OneOf_ColorFormat: Codable, Equatable, Sendable {
      /// Optional. SDR color format setting for H264.
      indirect case sdr(VideoStream.H264ColorFormatSDR?)
      /// Optional. HLG color format setting for H264.
      indirect case hlg(VideoStream.H264ColorFormatHLG?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.VideoStream.H264CodecSettings"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Convert the input video to a Standard Dynamic Range (SDR) video.
  public struct H265ColorFormatSDR: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `H265ColorFormatSDR`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = H265ColorFormatSDR().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.VideoStream.H265ColorFormatSDR"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Convert the input video to a Hybrid Log Gamma (HLG) video.
  public struct H265ColorFormatHLG: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `H265ColorFormatHLG`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = H265ColorFormatHLG().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.VideoStream.H265ColorFormatHLG"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Convert the input video to a High Dynamic Range 10 (HDR10) video.
  public struct H265ColorFormatHDR10: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `H265ColorFormatHDR10`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = H265ColorFormatHDR10().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.VideoStream.H265ColorFormatHDR10"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// H265 codec settings.
  public struct H265CodecSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The width of the video in pixels. Must be an even integer.
    /// When not specified, the width is adjusted to match the specified height
    /// and input aspect ratio. If both are omitted, the input width is used.
    ///
    /// For portrait videos that contain horizontal ASR and rotation metadata,
    /// provide the width, in pixels, per the horizontal ASR. The API calculates
    /// the height per the horizontal ASR. The API detects any rotation metadata
    /// and swaps the requested height and width for the output.
    public var widthPixels: Swift.Int32 = Swift.Int32()

    /// The height of the video in pixels. Must be an even integer.
    /// When not specified, the height is adjusted to match the specified width
    /// and input aspect ratio. If both are omitted, the input height is used.
    ///
    /// For portrait videos that contain horizontal ASR and rotation metadata,
    /// provide the height, in pixels, per the horizontal ASR. The API calculates
    /// the width per the horizontal ASR. The API detects any rotation metadata
    /// and swaps the requested height and width for the output.
    public var heightPixels: Swift.Int32 = Swift.Int32()

    /// Required. The target video frame rate in frames per second (FPS). Must be
    /// less than or equal to 120.
    public var frameRate: Swift.Double = Swift.Double()

    /// Optional. Frame rate conversion strategy for desired frame rate. The
    /// default is `DOWNSAMPLE`.
    public var frameRateConversionStrategy: VideoStream.FrameRateConversionStrategy =
      VideoStream.FrameRateConversionStrategy()

    /// Required. The video bitrate in bits per second. The minimum value is
    /// 1,000. The maximum value is 800,000,000.
    public var bitrateBps: Swift.Int32 = Swift.Int32()

    /// Pixel format to use. The default is `yuv420p`.
    ///
    /// Supported pixel formats:
    ///
    /// - `yuv420p` pixel format
    /// - `yuv422p` pixel format
    /// - `yuv444p` pixel format
    /// - `yuv420p10` 10-bit HDR pixel format
    /// - `yuv422p10` 10-bit HDR pixel format
    /// - `yuv444p10` 10-bit HDR pixel format
    /// - `yuv420p12` 12-bit HDR pixel format
    /// - `yuv422p12` 12-bit HDR pixel format
    /// - `yuv444p12` 12-bit HDR pixel format
    public var pixelFormat: Swift.String = Swift.String()

    /// Specify the mode. The default is `vbr`.
    ///
    /// Supported rate control modes:
    ///
    /// - `vbr` - variable bitrate
    /// - `crf` - constant rate factor
    public var rateControlMode: Swift.String = Swift.String()

    /// Target CRF level. Must be between 10 and 36, where 10 is the highest
    /// quality and 36 is the most efficient compression. The default is 21.
    public var crfLevel: Swift.Int32 = Swift.Int32()

    /// Specifies whether an open Group of Pictures (GOP) structure should be
    /// allowed or not. The default is `false`.
    public var allowOpenGop: Swift.Bool = Swift.Bool()

    /// Use two-pass encoding strategy to achieve better video quality.
    /// [H265CodecSettings.rate_control_mode][google.cloud.video.transcoder.v1.VideoStream.H265CodecSettings.rate_control_mode]
    /// must be `vbr`. The default is `false`.
    ///
    /// [google.cloud.video.transcoder.v1.VideoStream.H265CodecSettings.rate_control_mode]: <doc:VideoStream/H265CodecSettings/rateControlMode>
    public var enableTwoPass: Swift.Bool = Swift.Bool()

    /// Size of the Video Buffering Verifier (VBV) buffer in bits. Must be
    /// greater than zero. The default is equal to `VideoStream.bitrate_bps`.
    public var vbvSizeBits: Swift.Int32 = Swift.Int32()

    /// Initial fullness of the Video Buffering Verifier (VBV) buffer in bits.
    /// Must be greater than zero. The default is equal to 90% of
    /// [H265CodecSettings.vbv_size_bits][google.cloud.video.transcoder.v1.VideoStream.H265CodecSettings.vbv_size_bits].
    ///
    /// [google.cloud.video.transcoder.v1.VideoStream.H265CodecSettings.vbv_size_bits]: <doc:VideoStream/H265CodecSettings/vbvSizeBits>
    public var vbvFullnessBits: Swift.Int32 = Swift.Int32()

    /// Allow B-pyramid for reference frame selection. This may not be supported
    /// on all decoders. The default is `false`.
    public var bPyramid: Swift.Bool = Swift.Bool()

    /// The number of consecutive B-frames. Must be greater than or equal to
    /// zero. Must be less than
    /// [H265CodecSettings.gop_frame_count][google.cloud.video.transcoder.v1.VideoStream.H265CodecSettings.gop_frame_count]
    /// if set. The default is 0.
    ///
    /// [google.cloud.video.transcoder.v1.VideoStream.H265CodecSettings.gop_frame_count]: <doc:VideoStream/H265CodecSettings/OneOf_GopMode/gopFrameCount(_:)>
    public var bFrameCount: Swift.Int32 = Swift.Int32()

    /// Specify the intensity of the adaptive quantizer (AQ). Must be between 0
    /// and 1, where 0 disables the quantizer and 1 maximizes the quantizer. A
    /// higher value equals a lower bitrate but smoother image. The default is 0.
    public var aqStrength: Swift.Double = Swift.Double()

    /// Enforces the specified codec profile. The following profiles are
    /// supported:
    ///
    /// *   8-bit profiles
    ///     *   `main` (default)
    ///     *   `main-intra`
    ///     *   `mainstillpicture`
    /// *   10-bit profiles
    ///     *   `main10` (default)
    ///     *   `main10-intra`
    ///     *   `main422-10`
    ///     *   `main422-10-intra`
    ///     *   `main444-10`
    ///     *   `main444-10-intra`
    /// *   12-bit profiles
    ///     *   `main12` (default)
    ///     *   `main12-intra`
    ///     *   `main422-12`
    ///     *   `main422-12-intra`
    ///     *   `main444-12`
    ///     *   `main444-12-intra`
    ///
    /// The available options are
    /// [FFmpeg-compatible](https://x265.readthedocs.io/).
    /// Note that certain values for this field may cause the
    /// transcoder to override other fields you set in the `H265CodecSettings`
    /// message.
    public var profile: Swift.String = Swift.String()

    /// Enforces the specified codec tune. The available options are
    /// [FFmpeg-compatible](https://trac.ffmpeg.org/wiki/Encode/H.265).
    /// Note that certain values for this field may cause the
    /// transcoder to override other fields you set in the `H265CodecSettings`
    /// message.
    public var tune: Swift.String = Swift.String()

    /// Enforces the specified codec preset. The default is `veryfast`. The
    /// available options are
    /// [FFmpeg-compatible](https://trac.ffmpeg.org/wiki/Encode/H.265).
    /// Note that certain values for this field may cause the
    /// transcoder to override other fields you set in the `H265CodecSettings`
    /// message.
    public var preset: Swift.String = Swift.String()

    /// GOP mode can be either by frame count or duration.
    public var gopMode: OneOf_GopMode? = nil

    /// Color format can be sdr, hlg, hdr10.
    public var colorFormat: OneOf_ColorFormat? = nil

    /// Initialize a new instance of `H265CodecSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = H265CodecSettings().with { $0.widthPixels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case widthPixels = "widthPixels"
      case heightPixels = "heightPixels"
      case frameRate = "frameRate"
      case frameRateConversionStrategy = "frameRateConversionStrategy"
      case bitrateBps = "bitrateBps"
      case pixelFormat = "pixelFormat"
      case rateControlMode = "rateControlMode"
      case crfLevel = "crfLevel"
      case allowOpenGop = "allowOpenGop"
      case gopFrameCount = "gopFrameCount"
      case gopDuration = "gopDuration"
      case enableTwoPass = "enableTwoPass"
      case vbvSizeBits = "vbvSizeBits"
      case vbvFullnessBits = "vbvFullnessBits"
      case bPyramid = "bPyramid"
      case bFrameCount = "bFrameCount"
      case aqStrength = "aqStrength"
      case profile = "profile"
      case tune = "tune"
      case preset = "preset"
      case sdr = "sdr"
      case hlg = "hlg"
      case hdr10 = "hdr10"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.widthPixels = try container.decode(Swift.Int32.self, forKey: .widthPixels)
      self.heightPixels = try container.decode(Swift.Int32.self, forKey: .heightPixels)
      self.frameRate = try container.decode(Swift.Double.self, forKey: .frameRate)
      self.frameRateConversionStrategy = try container.decode(
        VideoStream.FrameRateConversionStrategy.self, forKey: .frameRateConversionStrategy)
      self.bitrateBps = try container.decode(Swift.Int32.self, forKey: .bitrateBps)
      self.pixelFormat = try container.decode(Swift.String.self, forKey: .pixelFormat)
      self.rateControlMode = try container.decode(Swift.String.self, forKey: .rateControlMode)
      self.crfLevel = try container.decode(Swift.Int32.self, forKey: .crfLevel)
      self.allowOpenGop = try container.decode(Swift.Bool.self, forKey: .allowOpenGop)
      self.enableTwoPass = try container.decode(Swift.Bool.self, forKey: .enableTwoPass)
      self.vbvSizeBits = try container.decode(Swift.Int32.self, forKey: .vbvSizeBits)
      self.vbvFullnessBits = try container.decode(Swift.Int32.self, forKey: .vbvFullnessBits)
      self.bPyramid = try container.decode(Swift.Bool.self, forKey: .bPyramid)
      self.bFrameCount = try container.decode(Swift.Int32.self, forKey: .bFrameCount)
      self.aqStrength = try container.decode(Swift.Double.self, forKey: .aqStrength)
      self.profile = try container.decode(Swift.String.self, forKey: .profile)
      self.tune = try container.decode(Swift.String.self, forKey: .tune)
      self.preset = try container.decode(Swift.String.self, forKey: .preset)

      var gopMode: OneOf_GopMode? = nil
      let gopModeCheckAndSet = {
        if gopMode != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'gopMode'"))
        }
        gopMode = $0
      }
      if let gopFrameCount = try container.decodeIfPresent(Swift.Int32.self, forKey: .gopFrameCount)
      {
        try gopModeCheckAndSet(.gopFrameCount(gopFrameCount))
      }
      if let gopDuration = try container.decodeIfPresent(
        GoogleCloudWkt.Duration?.self, forKey: .gopDuration)
      {
        try gopModeCheckAndSet(.gopDuration(gopDuration))
      }
      self.gopMode = gopMode

      var colorFormat: OneOf_ColorFormat? = nil
      let colorFormatCheckAndSet = {
        if colorFormat != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'colorFormat'"))
        }
        colorFormat = $0
      }
      if let sdr = try container.decodeIfPresent(VideoStream.H265ColorFormatSDR?.self, forKey: .sdr)
      {
        try colorFormatCheckAndSet(.sdr(sdr))
      }
      if let hlg = try container.decodeIfPresent(VideoStream.H265ColorFormatHLG?.self, forKey: .hlg)
      {
        try colorFormatCheckAndSet(.hlg(hlg))
      }
      if let hdr10 = try container.decodeIfPresent(
        VideoStream.H265ColorFormatHDR10?.self, forKey: .hdr10)
      {
        try colorFormatCheckAndSet(.hdr10(hdr10))
      }
      self.colorFormat = colorFormat
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.widthPixels, forKey: .widthPixels)
      try container.encode(self.heightPixels, forKey: .heightPixels)
      try container.encode(self.frameRate, forKey: .frameRate)
      try container.encode(self.frameRateConversionStrategy, forKey: .frameRateConversionStrategy)
      try container.encode(self.bitrateBps, forKey: .bitrateBps)
      try container.encode(self.pixelFormat, forKey: .pixelFormat)
      try container.encode(self.rateControlMode, forKey: .rateControlMode)
      try container.encode(self.crfLevel, forKey: .crfLevel)
      try container.encode(self.allowOpenGop, forKey: .allowOpenGop)
      try container.encode(self.enableTwoPass, forKey: .enableTwoPass)
      try container.encode(self.vbvSizeBits, forKey: .vbvSizeBits)
      try container.encode(self.vbvFullnessBits, forKey: .vbvFullnessBits)
      try container.encode(self.bPyramid, forKey: .bPyramid)
      try container.encode(self.bFrameCount, forKey: .bFrameCount)
      try container.encode(self.aqStrength, forKey: .aqStrength)
      try container.encode(self.profile, forKey: .profile)
      try container.encode(self.tune, forKey: .tune)
      try container.encode(self.preset, forKey: .preset)

      if let choice = self.gopMode {
        switch choice {
        case .gopFrameCount(let value):
          try container.encode(value, forKey: .gopFrameCount)
        case .gopDuration(let value):
          try container.encode(value, forKey: .gopDuration)
        }
      }

      if let choice = self.colorFormat {
        switch choice {
        case .sdr(let value):
          try container.encode(value, forKey: .sdr)
        case .hlg(let value):
          try container.encode(value, forKey: .hlg)
        case .hdr10(let value):
          try container.encode(value, forKey: .hdr10)
        }
      }
    }

    /// GOP mode can be either by frame count or duration.
    public enum OneOf_GopMode: Codable, Equatable, Sendable {
      /// Select the GOP size based on the specified frame count. Must be greater
      /// than zero.
      case gopFrameCount(Swift.Int32)
      /// Select the GOP size based on the specified duration. The default is
      /// `3s`. Note that `gopDuration` must be less than or equal to
      /// [`segmentDuration`](#SegmentSettings), and
      /// [`segmentDuration`](#SegmentSettings) must be divisible by
      /// `gopDuration`.
      indirect case gopDuration(GoogleCloudWkt.Duration?)
    }

    /// Color format can be sdr, hlg, hdr10.
    public enum OneOf_ColorFormat: Codable, Equatable, Sendable {
      /// Optional. SDR color format setting for H265.
      indirect case sdr(VideoStream.H265ColorFormatSDR?)
      /// Optional. HLG color format setting for H265.
      indirect case hlg(VideoStream.H265ColorFormatHLG?)
      /// Optional. HDR10 color format setting for H265.
      indirect case hdr10(VideoStream.H265ColorFormatHDR10?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.VideoStream.H265CodecSettings"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Convert the input video to a Standard Dynamic Range (SDR) video.
  public struct Vp9ColorFormatSDR: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `Vp9ColorFormatSDR`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Vp9ColorFormatSDR().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.VideoStream.Vp9ColorFormatSDR"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Convert the input video to a Hybrid Log Gamma (HLG) video.
  public struct Vp9ColorFormatHLG: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `Vp9ColorFormatHLG`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Vp9ColorFormatHLG().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.VideoStream.Vp9ColorFormatHLG"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// VP9 codec settings.
  public struct Vp9CodecSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The width of the video in pixels. Must be an even integer.
    /// When not specified, the width is adjusted to match the specified height
    /// and input aspect ratio. If both are omitted, the input width is used.
    ///
    /// For portrait videos that contain horizontal ASR and rotation metadata,
    /// provide the width, in pixels, per the horizontal ASR. The API calculates
    /// the height per the horizontal ASR. The API detects any rotation metadata
    /// and swaps the requested height and width for the output.
    public var widthPixels: Swift.Int32 = Swift.Int32()

    /// The height of the video in pixels. Must be an even integer.
    /// When not specified, the height is adjusted to match the specified width
    /// and input aspect ratio. If both are omitted, the input height is used.
    ///
    /// For portrait videos that contain horizontal ASR and rotation metadata,
    /// provide the height, in pixels, per the horizontal ASR. The API calculates
    /// the width per the horizontal ASR. The API detects any rotation metadata
    /// and swaps the requested height and width for the output.
    public var heightPixels: Swift.Int32 = Swift.Int32()

    /// Required. The target video frame rate in frames per second (FPS). Must be
    /// less than or equal to 120.
    public var frameRate: Swift.Double = Swift.Double()

    /// Optional. Frame rate conversion strategy for desired frame rate. The
    /// default is `DOWNSAMPLE`.
    public var frameRateConversionStrategy: VideoStream.FrameRateConversionStrategy =
      VideoStream.FrameRateConversionStrategy()

    /// Required. The video bitrate in bits per second. The minimum value is
    /// 1,000. The maximum value is 480,000,000.
    public var bitrateBps: Swift.Int32 = Swift.Int32()

    /// Pixel format to use. The default is `yuv420p`.
    ///
    /// Supported pixel formats:
    ///
    /// - `yuv420p` pixel format
    /// - `yuv422p` pixel format
    /// - `yuv444p` pixel format
    /// - `yuv420p10` 10-bit HDR pixel format
    /// - `yuv422p10` 10-bit HDR pixel format
    /// - `yuv444p10` 10-bit HDR pixel format
    /// - `yuv420p12` 12-bit HDR pixel format
    /// - `yuv422p12` 12-bit HDR pixel format
    /// - `yuv444p12` 12-bit HDR pixel format
    public var pixelFormat: Swift.String = Swift.String()

    /// Specify the mode. The default is `vbr`.
    ///
    /// Supported rate control modes:
    ///
    /// - `vbr` - variable bitrate
    public var rateControlMode: Swift.String = Swift.String()

    /// Target CRF level. Must be between 10 and 36, where 10 is the highest
    /// quality and 36 is the most efficient compression. The default is 21.
    ///
    /// **Note:** This field is not supported.
    public var crfLevel: Swift.Int32 = Swift.Int32()

    /// Enforces the specified codec profile. The following profiles are
    /// supported:
    ///
    /// *   `profile0` (default)
    /// *   `profile1`
    /// *   `profile2`
    /// *   `profile3`
    ///
    /// The available options are
    /// [WebM-compatible](https://www.webmproject.org/vp9/profiles/).
    /// Note that certain values for this field may cause the
    /// transcoder to override other fields you set in the `Vp9CodecSettings`
    /// message.
    public var profile: Swift.String = Swift.String()

    /// GOP mode can be either by frame count or duration.
    public var gopMode: OneOf_GopMode? = nil

    /// Color format can be sdr or hlg.
    public var colorFormat: OneOf_ColorFormat? = nil

    /// Initialize a new instance of `Vp9CodecSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Vp9CodecSettings().with { $0.widthPixels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case widthPixels = "widthPixels"
      case heightPixels = "heightPixels"
      case frameRate = "frameRate"
      case frameRateConversionStrategy = "frameRateConversionStrategy"
      case bitrateBps = "bitrateBps"
      case pixelFormat = "pixelFormat"
      case rateControlMode = "rateControlMode"
      case crfLevel = "crfLevel"
      case gopFrameCount = "gopFrameCount"
      case gopDuration = "gopDuration"
      case profile = "profile"
      case sdr = "sdr"
      case hlg = "hlg"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.widthPixels = try container.decode(Swift.Int32.self, forKey: .widthPixels)
      self.heightPixels = try container.decode(Swift.Int32.self, forKey: .heightPixels)
      self.frameRate = try container.decode(Swift.Double.self, forKey: .frameRate)
      self.frameRateConversionStrategy = try container.decode(
        VideoStream.FrameRateConversionStrategy.self, forKey: .frameRateConversionStrategy)
      self.bitrateBps = try container.decode(Swift.Int32.self, forKey: .bitrateBps)
      self.pixelFormat = try container.decode(Swift.String.self, forKey: .pixelFormat)
      self.rateControlMode = try container.decode(Swift.String.self, forKey: .rateControlMode)
      self.crfLevel = try container.decode(Swift.Int32.self, forKey: .crfLevel)
      self.profile = try container.decode(Swift.String.self, forKey: .profile)

      var gopMode: OneOf_GopMode? = nil
      let gopModeCheckAndSet = {
        if gopMode != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'gopMode'"))
        }
        gopMode = $0
      }
      if let gopFrameCount = try container.decodeIfPresent(Swift.Int32.self, forKey: .gopFrameCount)
      {
        try gopModeCheckAndSet(.gopFrameCount(gopFrameCount))
      }
      if let gopDuration = try container.decodeIfPresent(
        GoogleCloudWkt.Duration?.self, forKey: .gopDuration)
      {
        try gopModeCheckAndSet(.gopDuration(gopDuration))
      }
      self.gopMode = gopMode

      var colorFormat: OneOf_ColorFormat? = nil
      let colorFormatCheckAndSet = {
        if colorFormat != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'colorFormat'"))
        }
        colorFormat = $0
      }
      if let sdr = try container.decodeIfPresent(VideoStream.Vp9ColorFormatSDR?.self, forKey: .sdr)
      {
        try colorFormatCheckAndSet(.sdr(sdr))
      }
      if let hlg = try container.decodeIfPresent(VideoStream.Vp9ColorFormatHLG?.self, forKey: .hlg)
      {
        try colorFormatCheckAndSet(.hlg(hlg))
      }
      self.colorFormat = colorFormat
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.widthPixels, forKey: .widthPixels)
      try container.encode(self.heightPixels, forKey: .heightPixels)
      try container.encode(self.frameRate, forKey: .frameRate)
      try container.encode(self.frameRateConversionStrategy, forKey: .frameRateConversionStrategy)
      try container.encode(self.bitrateBps, forKey: .bitrateBps)
      try container.encode(self.pixelFormat, forKey: .pixelFormat)
      try container.encode(self.rateControlMode, forKey: .rateControlMode)
      try container.encode(self.crfLevel, forKey: .crfLevel)
      try container.encode(self.profile, forKey: .profile)

      if let choice = self.gopMode {
        switch choice {
        case .gopFrameCount(let value):
          try container.encode(value, forKey: .gopFrameCount)
        case .gopDuration(let value):
          try container.encode(value, forKey: .gopDuration)
        }
      }

      if let choice = self.colorFormat {
        switch choice {
        case .sdr(let value):
          try container.encode(value, forKey: .sdr)
        case .hlg(let value):
          try container.encode(value, forKey: .hlg)
        }
      }
    }

    /// GOP mode can be either by frame count or duration.
    public enum OneOf_GopMode: Codable, Equatable, Sendable {
      /// Select the GOP size based on the specified frame count. Must be greater
      /// than zero.
      case gopFrameCount(Swift.Int32)
      /// Select the GOP size based on the specified duration. The default is
      /// `3s`. Note that `gopDuration` must be less than or equal to
      /// [`segmentDuration`](#SegmentSettings), and
      /// [`segmentDuration`](#SegmentSettings) must be divisible by
      /// `gopDuration`.
      indirect case gopDuration(GoogleCloudWkt.Duration?)
    }

    /// Color format can be sdr or hlg.
    public enum OneOf_ColorFormat: Codable, Equatable, Sendable {
      /// Optional. SDR color format setting for VP9.
      indirect case sdr(VideoStream.Vp9ColorFormatSDR?)
      /// Optional. HLG color format setting for VP9.
      indirect case hlg(VideoStream.Vp9ColorFormatHLG?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.VideoStream.Vp9CodecSettings"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The conversion strategy for desired frame rate.
  public enum FrameRateConversionStrategy: Codable, Equatable, Sendable {
    /// Unspecified frame rate conversion strategy.
    case unspecified
    /// Selectively retain frames to reduce the output frame rate.
    /// Every _n_ th frame is kept, where `n = ceil(input frame rate / target
    /// frame rate)`. When _n_ = 1 (that is, the target frame rate is greater
    /// than the input frame rate), the output frame rate matches the input frame
    /// rate. When _n_ > 1, frames are dropped and the output frame rate is
    /// equal to `(input frame rate / n)`. For more information, see
    /// [Calculate frame
    /// rate](https://cloud.google.com/transcoder/docs/concepts/frame-rate).
    case downsample
    /// Drop or duplicate frames to match the specified frame rate.
    case dropDuplicate
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .downsample: return 1
      case .dropDuplicate: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FRAME_RATE_CONVERSION_STRATEGY_UNSPECIFIED"
      case .downsample: return "DOWNSAMPLE"
      case .dropDuplicate: return "DROP_DUPLICATE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FrameRateConversionStrategy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FRAME_RATE_CONVERSION_STRATEGY_UNSPECIFIED": self = .unspecified
      case "DOWNSAMPLE": self = .downsample
      case "DROP_DUPLICATE": self = .dropDuplicate
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FrameRateConversionStrategy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .downsample
      case 2: self = .dropDuplicate
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .downsample: return try container.encode(1)
      case .dropDuplicate: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Codec settings can be h264, h265, or vp9.
  public enum OneOf_CodecSettings: Codable, Equatable, Sendable {
    /// H264 codec settings.
    indirect case h264(VideoStream.H264CodecSettings?)
    /// H265 codec settings.
    indirect case h265(VideoStream.H265CodecSettings?)
    /// VP9 codec settings.
    indirect case vp9(VideoStream.Vp9CodecSettings?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.VideoStream"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
